// Package emitter implements LO/NORTHSTAR.md's Phase 1 real acceptance bar: emit real `.prn`
// text from a parsed LO Program, calling into PARENA's own `stdlib/base4/algebra.prn` and
// `stdlib/base4/vector.prn` rather than hand-generating base4 bit logic inline (founder
// real-time, per NORTHSTAR.md's "groundwork already started" section: "ffi into parena is
// acceptable if it satisfies the design").
//
// Real, deliberately narrow v0, matching the parser's own covered subset: emits one `main`
// function whose body is the program's Ternary/Arith/Eq/State expression tree, wrapped in a
// `(defn main [] : I32 ...)` (or the Door's declared type, when scalar). Real, honest limitation:
// only the scalar I32 path is covered — a Door declaring Vector/Matrix/Pattern/String/Func/Void
// is a real, separate follow-up (Phase 1's own NORTHSTAR text explicitly scopes to "scalars and
// flat structs only" for this reason).
package emitter

import (
	"fmt"
	"strings"

	"github.com/emilyspringerton/LO/internal/lexer"
	"github.com/emilyspringerton/LO/internal/parser"
)

// Error is an emit-time failure — a real, named unsupported construct, not a silent fallback.
type Error struct{ Msg string }

func (e *Error) Error() string { return "emit error: " + e.Msg }

// Emit produces real `.prn` source for prog. Real, current scope: prog.DoorType must be
// TypeI32 or unset (TypeInvalid) — anything else is a named, honest error, not guessed at.
func Emit(prog *parser.Program) (string, error) {
	if prog.HasDoor && prog.DoorType != parser.TypeI32 {
		return "", &Error{Msg: "only a DOOR I32 (or no Door) is supported in this v0"}
	}

	body, err := emitExpr(prog.Body)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(";; Generated by the LO compiler (Phase 1, internal/emitter) -- do not edit by hand.\n")
	b.WriteString("(module lo/main)\n")
	b.WriteString("(import base4/algebra)\n")
	b.WriteString("(export main)\n\n")
	b.WriteString("(defn main [] : I32\n  ")
	b.WriteString(body)
	b.WriteString(")\n")
	return b.String(), nil
}

// Real, live-verified finding, worth naming rather than assumed either way: naming this defn
// "main" isn't a designed PARENA "entry point" feature (grepped src/emit.c directly -- there is
// no special-casing of the string "main" anywhere in the mangler or emitter). It works purely
// because PARENA's own name-mangling leaves a plain, hyphen-free identifier like "main"
// untouched, which happens to collide with C's own real `int main(void)` entry point. Confirmed
// end-to-end: `parena build stdlib/base4/algebra.prn <generated .prn> -o out.c && cc out.c
// runtime/parena_runtime.c -o out && ./out` produces a real, standalone, runnable executable
// whose exit code is the program's own real result (verified: the XOR example above exits 2,
// matching 1 XOR 3 = 2 by hand). A real, useful coincidence for this v0's demo purposes, not a
// documented compiler guarantee -- don't rely on it surviving a future emit.c change.

func emitExpr(e parser.Expr) (string, error) {
	switch v := e.(type) {
	case parser.State:
		return fmt.Sprintf("%d", v.Value), nil

	case parser.Let:
		// Real, direct lowering to PARENA's own `let` (see NORTHSTAR.md/GRAMMAR.md's own
		// "Let" doc comment for why this sidesteps the source spec's own De Bruijn/environment-
		// matrix blowup risk entirely). A single fixed binding name `x` is enough for this v0's
		// real, narrow "exactly one active binding, innermost shadows" scope -- PARENA's own
		// `let` already shadows correctly on a repeated name, so nested LO `Let`s translate to
		// nested PARENA `let`s with the SAME name, and `LetRef` always resolves to the
		// innermost one, matching GRAMMAR.md's own documented semantics exactly.
		bound, err := emitExpr(v.Bound)
		if err != nil {
			return "", err
		}
		body, err := emitExpr(v.Body)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(let [x %s] %s)", bound, body), nil

	case parser.LetRef:
		return "x", nil

	case parser.VoidExpr:
		// Real, honest v0 stand-in: LO's VOID has no direct PARENA I32 equivalent in this
		// scalar-only path -- 0 is used as a placeholder, named here rather than silently
		// treated as semantically meaningful. A real Option/Unit-typed emission is a separate
		// follow-up once a non-scalar Door type is supported.
		return "0", nil

	case parser.Eq:
		left, err := emitExpr(v.Left)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(v.Right)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(= %s %s)", left, right), nil

	case parser.Arith:
		left, err := emitExpr(v.Left)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(v.Right)
		if err != nil {
			return "", err
		}
		fn, err := arithFn(v.Op)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(base4/algebra/%s %s %s)", fn, left, right), nil

	case parser.Ternary:
		cond, err := emitExpr(v.Cond)
		if err != nil {
			return "", err
		}
		trueExpr, err := emitExpr(v.True)
		if err != nil {
			return "", err
		}
		falseExpr, err := emitExpr(v.False)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(if %s %s %s)", cond, trueExpr, falseExpr), nil

	default:
		return "", &Error{Msg: fmt.Sprintf("unsupported expression node %T", e)}
	}
}

func arithFn(op lexer.Kind) (string, error) {
	switch op {
	case lexer.KindPlus4:
		return "base4-add", nil
	case lexer.KindMinus4:
		return "base4-subtract", nil
	case lexer.KindAnd4:
		return "base4-and", nil
	case lexer.KindOr4:
		return "base4-or", nil
	case lexer.KindXor4:
		return "base4-xor", nil
	default:
		return "", &Error{Msg: fmt.Sprintf("unsupported arithmetic operator %s", op)}
	}
}
