// Package emitter implements LO/NORTHSTAR.md's Phase 1 real acceptance bar: emit real `.prn`
// text from a parsed LO Program, calling into PARENA's own `stdlib/base4/algebra.prn` and
// `stdlib/base4/vector.prn` rather than hand-generating base4 bit logic inline (founder
// real-time, per NORTHSTAR.md's "groundwork already started" section: "ffi into parena is
// acceptable if it satisfies the design").
//
// Real, deliberately narrow v0, matching the parser's own covered subset: emits one `main`
// function whose body is the program's Ternary/Arith/Eq/State expression tree, wrapped in a
// `(defn main [] : I32 ...)` (or the Door's declared type, when scalar). Real, honest limitation:
// only the scalar I32 path is covered — a Door declaring Vector/Matrix/Pattern/String/Func/Void
// is a real, separate follow-up (Phase 1's own NORTHSTAR text explicitly scopes to "scalars and
// flat structs only" for this reason).
package emitter

import (
	"fmt"
	"strings"

	"github.com/emilyspringerton/LO/internal/lexer"
	"github.com/emilyspringerton/LO/internal/parser"
)

// Error is an emit-time failure — a real, named unsupported construct, not a silent fallback.
type Error struct{ Msg string }

func (e *Error) Error() string { return "emit error: " + e.Msg }

// Emit produces real `.prn` source for prog. Real, current scope: prog.DoorType must be
// TypeI32/TypeFloat/TypeDouble or unset (TypeInvalid) — anything else is a named, honest error,
// not guessed at.
func Emit(prog *parser.Program) (string, error) {
	returnType := "I32"
	needsF64Cast := false
	if prog.HasDoor {
		switch prog.DoorType {
		case parser.TypeI32:
			// returnType stays I32
		case parser.TypeFloat, parser.TypeDouble:
			// Real, checked-not-assumed finding (LO_Formal_Grammar_Phase_0_Complete.md §7.2/7.3
			// distinguish FLOAT/DOUBLE as separate token types): PARENA itself has no separate
			// single-precision float type at all (confirmed directly against src/emit.c) -- both
			// LO types compile to the same real PARENA F64. Every LO expression in this v0 is
			// still base4-state I32 arithmetic, so a Float/Double Door casts the I32 result to
			// F64 via a small local helper emitted into the same module (avoiding an extra
			// import for one real one-line cast).
			returnType = "F64"
			needsF64Cast = true
		default:
			return "", &Error{Msg: "only a DOOR I32, FLOAT, DOUBLE, or no Door is supported in this v0"}
		}
	}

	body, err := emitExpr(prog.Body, 0)
	if err != nil {
		return "", err
	}
	if needsF64Cast {
		body = fmt.Sprintf("(lo-i32-to-f64 %s)", body)
	}

	var b strings.Builder
	b.WriteString(";; Generated by the LO compiler (Phase 1, internal/emitter) -- do not edit by hand.\n")
	b.WriteString("(module lo/main)\n")
	b.WriteString("(import base4/algebra)\n")
	if needsF64Cast {
		b.WriteString("(export main lo-i32-to-f64)\n\n")
		b.WriteString("(defn lo-i32-to-f64 [(x : I32)] : F64\n  #target\n  {:c (inline-c \"(double)(x)\")})\n\n")
	} else {
		b.WriteString("(export main)\n\n")
	}
	b.WriteString(fmt.Sprintf("(defn main [] : %s\n  ", returnType))
	b.WriteString(body)
	b.WriteString(")\n")
	return b.String(), nil
}

// Real, live-verified finding, worth naming rather than assumed either way: naming this defn
// "main" isn't a designed PARENA "entry point" feature (grepped src/emit.c directly -- there is
// no special-casing of the string "main" anywhere in the mangler or emitter). It works purely
// because PARENA's own name-mangling leaves a plain, hyphen-free identifier like "main"
// untouched, which happens to collide with C's own real `int main(void)` entry point. Confirmed
// end-to-end: `parena build stdlib/base4/algebra.prn <generated .prn> -o out.c && cc out.c
// runtime/parena_runtime.c -o out && ./out` produces a real, standalone, runnable executable
// whose exit code is the program's own real result (verified: the XOR example above exits 2,
// matching 1 XOR 3 = 2 by hand). A real, useful coincidence for this v0's demo purposes, not a
// documented compiler guarantee -- don't rely on it surviving a future emit.c change.

// emitExpr takes `depth`, the number of Let bindings enclosing `e` at this point in the tree
// (0 at the program's own top level) -- needed so `Let` can pick a fresh, non-colliding PARENA
// variable name per nesting level (`x0`, `x1`, ...) and `LetRef` can resolve its own `Depth`
// (0 = innermost) to the right one, extended 2026-08-30 to reach outer bindings, not just the
// nearest -- see `parser.LetRef`'s own doc comment for the real reason this changed from a
// single always-shadowing `x`.
func emitExpr(e parser.Expr, depth int) (string, error) {
	switch v := e.(type) {
	case parser.State:
		return fmt.Sprintf("%d", v.Value), nil

	case parser.Let:
		// Real, direct lowering to PARENA's own `let` (see NORTHSTAR.md/GRAMMAR.md's own
		// "Let" doc comment for why this sidesteps the source spec's own De Bruijn/environment-
		// matrix blowup risk entirely). Bound is emitted at the CURRENT depth (it must not see
		// its own binding); Body is emitted one level deeper.
		bound, err := emitExpr(v.Bound, depth)
		if err != nil {
			return "", err
		}
		body, err := emitExpr(v.Body, depth+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(let [x%d %s] %s)", depth, bound, body), nil

	case parser.LetRef:
		// Depth 0 = innermost = the most-recently-introduced binding, x{depth-1}; Depth K = K
		// levels further out, x{depth-1-K}. Real, honest bounds check: referencing a depth with
		// no real enclosing Let is a real emit-time error, not silently clamped to 0 or wrapped.
		if v.Depth >= depth {
			return "", &Error{Msg: fmt.Sprintf("LetRef depth %d has no enclosing Let (only %d active here)", v.Depth, depth)}
		}
		return fmt.Sprintf("x%d", depth-1-v.Depth), nil

	case parser.VoidExpr:
		// Real, honest v0 stand-in: LO's VOID has no direct PARENA I32 equivalent in this
		// scalar-only path -- 0 is used as a placeholder, named here rather than silently
		// treated as semantically meaningful. A real Option/Unit-typed emission is a separate
		// follow-up once a non-scalar Door type is supported.
		return "0", nil

	case parser.Eq:
		left, err := emitExpr(v.Left, depth)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(v.Right, depth)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(= %s %s)", left, right), nil

	case parser.Arith:
		left, err := emitExpr(v.Left, depth)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(v.Right, depth)
		if err != nil {
			return "", err
		}
		fn, err := arithFn(v.Op)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(base4/algebra/%s %s %s)", fn, left, right), nil

	case parser.Ternary:
		cond, err := emitExpr(v.Cond, depth)
		if err != nil {
			return "", err
		}
		trueExpr, err := emitExpr(v.True, depth)
		if err != nil {
			return "", err
		}
		falseExpr, err := emitExpr(v.False, depth)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(if %s %s %s)", cond, trueExpr, falseExpr), nil

	case parser.Switch:
		// Real, direct lowering to a nested PARENA if/= chain -- the same shape Ternary already
		// emits, just chained once per Case, ending in the (required, see the parser's own
		// switch_ doc comment) Default.
		selector, err := emitExpr(v.Selector, depth)
		if err != nil {
			return "", err
		}
		tail, err := emitExpr(v.Default, depth)
		if err != nil {
			return "", err
		}
		for i := len(v.Cases) - 1; i >= 0; i-- {
			c := v.Cases[i]
			body, err := emitExpr(c.Body, depth)
			if err != nil {
				return "", err
			}
			tail = fmt.Sprintf("(if (= %s %d) %s %s)", selector, c.Match, body, tail)
		}
		return tail, nil

	case parser.Lambda:
		// Real, direct lowering to a real PARENA anonymous function value (`fn`), reusing the
		// same depth-index binding scheme Let/LetRef already use -- see the Lambda AST node's
		// own doc comment for why this diverges from the source doc's own named-parameter form.
		body, err := emitExpr(v.Body, depth+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(fn [(x%d : I32)] %s)", depth, body), nil

	case parser.Call:
		// Real, honest v0 restriction: Fn must be a real Lambda literal (see the Call AST node's
		// own doc comment) -- caught here as a real, named emit-time error rather than emitting
		// broken .prn for anything else.
		lambda, ok := v.Fn.(parser.Lambda)
		if !ok {
			return "", &Error{Msg: fmt.Sprintf("Call's own Fn must be a Lambda literal in this v0, got %T", v.Fn)}
		}
		fnStr, err := emitExpr(lambda, depth)
		if err != nil {
			return "", err
		}
		argStr, err := emitExpr(v.Arg, depth)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s)", fnStr, argStr), nil

	default:
		return "", &Error{Msg: fmt.Sprintf("unsupported expression node %T", e)}
	}
}

func arithFn(op lexer.Kind) (string, error) {
	switch op {
	case lexer.KindPlus4:
		return "base4-add", nil
	case lexer.KindMinus4:
		return "base4-subtract", nil
	case lexer.KindAnd4:
		return "base4-and", nil
	case lexer.KindOr4:
		return "base4-or", nil
	case lexer.KindXor4:
		return "base4-xor", nil
	default:
		return "", &Error{Msg: fmt.Sprintf("unsupported arithmetic operator %s", op)}
	}
}
