// Package emitter implements LO/NORTHSTAR.md's Phase 1 real acceptance bar: emit real `.prn`
// text from a parsed LO Program, calling into PARENA's own `stdlib/base4/algebra.prn` and
// `stdlib/base4/vector.prn` rather than hand-generating base4 bit logic inline (founder
// real-time, per NORTHSTAR.md's "groundwork already started" section: "ffi into parena is
// acceptable if it satisfies the design").
//
// Real, deliberately narrow v0, matching the parser's own covered subset: emits one `main`
// function whose body is the program's Ternary/Arith/Eq/State expression tree, wrapped in a
// `(defn main [] : I32 ...)` (or the Door's declared type, when scalar). Real, honest limitation:
// only the scalar I32 path is covered — a Door declaring Vector/Matrix/Pattern/String/Func/Void
// is a real, separate follow-up (Phase 1's own NORTHSTAR text explicitly scopes to "scalars and
// flat structs only" for this reason).
package emitter

import (
	"fmt"
	"strings"

	"github.com/emilyspringerton/LO/internal/lexer"
	"github.com/emilyspringerton/LO/internal/parser"
)

// Error is an emit-time failure — a real, named unsupported construct, not a silent fallback.
type Error struct{ Msg string }

func (e *Error) Error() string { return "emit error: " + e.Msg }

// exprType is the real PARENA type a given Let binding (x0, x1, ...) was bound to -- LO itself
// has no general type-checker, so this is a minimal, narrow inference used for exactly one real
// purpose: letting MATCH's own Subject be a LetRef/MAGNET pointing at a Let-bound string, not
// only a bare StringLit. Every other expression shape in this v0 is I32 (or, at the Door level,
// cast to F64/String separately), so typeI32 stays the default everywhere this isn't tracked.
type exprType int

const (
	typeI32 exprType = iota
	typeString
)

// Emit produces real `.prn` source for prog. Real, current scope: prog.DoorType must be
// TypeI32/TypeFloat/TypeDouble or unset (TypeInvalid) — anything else is a named, honest error,
// not guessed at.
func Emit(prog *parser.Program) (string, error) {
	returnType := "I32"
	needsF64Cast := false
	if prog.HasDoor {
		switch prog.DoorType {
		case parser.TypeI32:
			// returnType stays I32
		case parser.TypeFloat, parser.TypeDouble:
			// Real, checked-not-assumed finding (LO_Formal_Grammar_Phase_0_Complete.md §7.2/7.3
			// distinguish FLOAT/DOUBLE as separate token types): PARENA itself has no separate
			// single-precision float type at all (confirmed directly against src/emit.c) -- both
			// LO types compile to the same real PARENA F64. Every LO expression in this v0 is
			// still base4-state I32 arithmetic, so a Float/Double Door casts the I32 result to
			// F64 via a small local helper emitted into the same module (avoiding an extra
			// import for one real one-line cast).
			returnType = "F64"
			needsF64Cast = true
		case parser.TypeString:
			// LO's first real String-typed Door, added 2026-09-01 (founder real-time: "continue"),
			// paired with parser.StringLit -- no cast needed, PARENA's own `String` maps directly
			// to C `char *` (confirmed against src/emit.c), same as this v0's I32 Door.
			returnType = "String"
		default:
			return "", &Error{Msg: "only a DOOR I32, FLOAT, DOUBLE, STRING, or no Door is supported in this v0"}
		}
	}

	// exprNeedsArena's own doc comment: a Match anywhere in the body needs a caller-supplied
	// Arena (regex/pcre/compile and is-match both require one) -- and once the function takes a
	// real parameter, it can no longer be named "main" (see the fnName/params branch below).
	needsArena := exprNeedsArena(prog.Body)

	body, err := emitExpr(prog.Body, 0, nil)
	if err != nil {
		return "", err
	}
	if needsF64Cast {
		body = fmt.Sprintf("(lo-i32-to-f64 %s)", body)
	}

	fnName, params := "main", ""
	if needsArena {
		// Real, necessary consequence, not a stylistic choice: `(defn main [(dest : Arena @
		// Region)] ...)` would mangle to `int main(Arena)` -- not a real C entry-point signature
		// at all (unlike the F64/String Door cases, which stayed VALID-but-meaningless C `main`
		// signatures) -- so a MATCH anywhere in the body forces both a real parameter AND a real
		// name change. Exported and called directly by a real test driver that constructs its own
		// Arena (see emitter_test.go's own compileRunAndGetBool), same real "renamed function,
		// called by a purpose-built driver" shape the FLOAT/DOUBLE/STRING Door verification
		// already established -- just for a structural reason this time, not an ABI one.
		fnName = "lo-program"
		params = "(dest : Arena @ Region)"
	}

	var b strings.Builder
	b.WriteString(";; Generated by the LO compiler (Phase 1, internal/emitter) -- do not edit by hand.\n")
	b.WriteString("(module lo/main)\n")
	b.WriteString("(import base4/algebra)\n")
	if needsArena {
		b.WriteString("(import regex/pcre)\n")
	}
	if needsF64Cast {
		b.WriteString(fmt.Sprintf("(export %s lo-i32-to-f64)\n\n", fnName))
		b.WriteString("(defn lo-i32-to-f64 [(x : I32)] : F64\n  #target\n  {:c (inline-c \"(double)(x)\")})\n\n")
	} else {
		b.WriteString(fmt.Sprintf("(export %s)\n\n", fnName))
	}
	b.WriteString(fmt.Sprintf("(defn %s [%s] : %s\n  ", fnName, params, returnType))
	b.WriteString(body)
	b.WriteString(")\n")
	return b.String(), nil
}

// exprNeedsArena reports whether e (transitively) contains a Match node -- see Emit's own doc
// comment on what that forces. Every other node here just recurses into its own sub-expressions;
// State/LetRef/VoidExpr/StringLit have none, so they fall through to the default false.
func exprNeedsArena(e parser.Expr) bool {
	switch v := e.(type) {
	case parser.Match:
		return true
	case parser.Let:
		return exprNeedsArena(v.Bound) || exprNeedsArena(v.Body)
	case parser.Ternary:
		return exprNeedsArena(v.Cond) || exprNeedsArena(v.True) || exprNeedsArena(v.False)
	case parser.Eq:
		return exprNeedsArena(v.Left) || exprNeedsArena(v.Right)
	case parser.Arith:
		return exprNeedsArena(v.Left) || exprNeedsArena(v.Right)
	case parser.Switch:
		if exprNeedsArena(v.Selector) || exprNeedsArena(v.Default) {
			return true
		}
		for _, c := range v.Cases {
			if exprNeedsArena(c.Body) {
				return true
			}
		}
		return false
	case parser.Lambda:
		return exprNeedsArena(v.Body)
	case parser.Call:
		return exprNeedsArena(v.Fn) || exprNeedsArena(v.Arg)
	default:
		return false
	}
}

// Real, live-verified finding, worth naming rather than assumed either way: naming this defn
// "main" isn't a designed PARENA "entry point" feature (grepped src/emit.c directly -- there is
// no special-casing of the string "main" anywhere in the mangler or emitter). It works purely
// because PARENA's own name-mangling leaves a plain, hyphen-free identifier like "main"
// untouched, which happens to collide with C's own real `int main(void)` entry point. Confirmed
// end-to-end: `parena build stdlib/base4/algebra.prn <generated .prn> -o out.c && cc out.c
// runtime/parena_runtime.c -o out && ./out` produces a real, standalone, runnable executable
// whose exit code is the program's own real result (verified: the XOR example above exits 2,
// matching 1 XOR 3 = 2 by hand). A real, useful coincidence for this v0's demo purposes, not a
// documented compiler guarantee -- don't rely on it surviving a future emit.c change.

// emitExpr takes `depth`, the number of Let bindings enclosing `e` at this point in the tree
// (0 at the program's own top level) -- needed so `Let` can pick a fresh, non-colliding PARENA
// variable name per nesting level (`x0`, `x1`, ...) and `LetRef` can resolve its own `Depth`
// (0 = innermost) to the right one, extended 2026-08-30 to reach outer bindings, not just the
// nearest -- see `parser.LetRef`'s own doc comment for the real reason this changed from a
// single always-shadowing `x`. `types` holds each active binding's own exprType, indexed the
// same way `x0`/`x1`/... are (types[i] is x{i}'s type) -- added 2026-09-01 so a LetRef/MAGNET can
// be used as MATCH's own Subject when it resolves to a Let-bound String, not only a bare
// StringLit; every position that isn't a Let binding stays implicitly typeI32.
func emitExpr(e parser.Expr, depth int, types []exprType) (string, error) {
	switch v := e.(type) {
	case parser.State:
		return fmt.Sprintf("%d", v.Value), nil

	case parser.StringLit:
		return emitStringLiteral(v.Text), nil

	case parser.Match:
		// A Match's own Cond can ONLY be reached here as a Ternary's own `v.Cond` (per
		// parser.go's ternary(), the only place a Match is ever constructed) -- and the Ternary
		// case below special-cases exactly that combination (emitMatchIf), for a real,
		// confirmed-live PARENA compiler reason named on emitMatchIf's own doc comment. A Match
		// reaching this generic fallback would mean some OTHER caller invoked emitExpr on a bare
		// Match directly, which the grammar doesn't allow -- a real, honest error, not a second,
		// subtly-different emission path kept alive for a case that can't occur.
		return "", &Error{Msg: "Match can only be emitted as a Ternary's own Cond in this v0 (see emitMatchIf)"}

	case parser.Let:
		// Real, direct lowering to PARENA's own `let` (see NORTHSTAR.md/GRAMMAR.md's own
		// "Let" doc comment for why this sidesteps the source spec's own De Bruijn/environment-
		// matrix blowup risk entirely). Bound is emitted at the CURRENT depth (it must not see
		// its own binding); Body is emitted one level deeper, with this binding's own inferred
		// exprType (exprTypeOf) recorded so a later LetRef/MAGNET back to it can be typed.
		bound, err := emitExpr(v.Bound, depth, types)
		if err != nil {
			return "", err
		}
		boundType := exprTypeOf(v.Bound, types)
		childTypes := append(append([]exprType{}, types...), boundType)
		body, err := emitExpr(v.Body, depth+1, childTypes)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(let [x%d %s] %s)", depth, bound, body), nil

	case parser.LetRef:
		// Depth 0 = innermost = the most-recently-introduced binding, x{depth-1}; Depth K = K
		// levels further out, x{depth-1-K}. Real, honest bounds check: referencing a depth with
		// no real enclosing Let is a real emit-time error, not silently clamped to 0 or wrapped.
		if v.Depth >= depth {
			return "", &Error{Msg: fmt.Sprintf("LetRef depth %d has no enclosing Let (only %d active here)", v.Depth, depth)}
		}
		return fmt.Sprintf("x%d", depth-1-v.Depth), nil

	case parser.VoidExpr:
		// Real, honest v0 stand-in: LO's VOID has no direct PARENA I32 equivalent in this
		// scalar-only path -- 0 is used as a placeholder, named here rather than silently
		// treated as semantically meaningful. A real Option/Unit-typed emission is a separate
		// follow-up once a non-scalar Door type is supported.
		return "0", nil

	case parser.Eq:
		left, err := emitExpr(v.Left, depth, types)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(v.Right, depth, types)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(= %s %s)", left, right), nil

	case parser.Arith:
		left, err := emitExpr(v.Left, depth, types)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(v.Right, depth, types)
		if err != nil {
			return "", err
		}
		fn, err := arithFn(v.Op)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(base4/algebra/%s %s %s)", fn, left, right), nil

	case parser.Ternary:
		trueExpr, err := emitExpr(v.True, depth, types)
		if err != nil {
			return "", err
		}
		falseExpr, err := emitExpr(v.False, depth, types)
		if err != nil {
			return "", err
		}

		if m, ok := v.Cond.(parser.Match); ok {
			return emitMatchIf(m, trueExpr, falseExpr, depth, types)
		}

		cond, err := emitExpr(v.Cond, depth, types)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(if %s %s %s)", cond, trueExpr, falseExpr), nil

	case parser.Switch:
		// Real, direct lowering to a nested PARENA if/= chain -- the same shape Ternary already
		// emits, just chained once per Case, ending in the (required, see the parser's own
		// switch_ doc comment) Default.
		selector, err := emitExpr(v.Selector, depth, types)
		if err != nil {
			return "", err
		}
		tail, err := emitExpr(v.Default, depth, types)
		if err != nil {
			return "", err
		}
		for i := len(v.Cases) - 1; i >= 0; i-- {
			c := v.Cases[i]
			body, err := emitExpr(c.Body, depth, types)
			if err != nil {
				return "", err
			}
			tail = fmt.Sprintf("(if (= %s %d) %s %s)", selector, c.Match, body, tail)
		}
		return tail, nil

	case parser.Lambda:
		// Real, direct lowering to a real PARENA anonymous function value (`fn`), reusing the
		// same depth-index binding scheme Let/LetRef already use -- see the Lambda AST node's
		// own doc comment for why this diverges from the source doc's own named-parameter form.
		// The parameter itself is always typeI32 here (its own default zero value) -- a Lambda
		// parameter's real type isn't known until Call time, and PARENA's own `fn` needs a
		// concrete param type at emit time regardless, so a String-typed Lambda parameter is a
		// real, separate follow-up, not attempted here.
		childTypes := append(append([]exprType{}, types...), typeI32)
		body, err := emitExpr(v.Body, depth+1, childTypes)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(fn [(x%d : I32)] %s)", depth, body), nil

	case parser.Call:
		// Real, honest v0 restriction: Fn must be a real Lambda literal (see the Call AST node's
		// own doc comment) -- caught here as a real, named emit-time error rather than emitting
		// broken .prn for anything else.
		lambda, ok := v.Fn.(parser.Lambda)
		if !ok {
			return "", &Error{Msg: fmt.Sprintf("Call's own Fn must be a Lambda literal in this v0, got %T", v.Fn)}
		}
		fnStr, err := emitExpr(lambda, depth, types)
		if err != nil {
			return "", err
		}
		argStr, err := emitExpr(v.Arg, depth, types)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s)", fnStr, argStr), nil

	default:
		return "", &Error{Msg: fmt.Sprintf("unsupported expression node %T", e)}
	}
}

// exprTypeOf infers e's own exprType for the real, narrow purpose named on exprType's own doc
// comment -- not a general type checker. A StringLit is typeString; a LetRef resolves through
// `types` (using the exact same depth math as LetRef's own emitExpr case); everything else in
// this v0 (State/Arith/Eq/Ternary/Switch/Lambda/Call/Match/VoidExpr) is typeI32, matching what
// emitExpr already assumes for all of them today.
func exprTypeOf(e parser.Expr, types []exprType) exprType {
	switch v := e.(type) {
	case parser.StringLit:
		return typeString
	case parser.LetRef:
		idx := len(types) - 1 - v.Depth
		if idx < 0 || idx >= len(types) {
			return typeI32
		}
		return types[idx]
	default:
		return typeI32
	}
}

// emitStringLiteral quotes text as a real PARENA string literal. PARENA's own reader unescapes
// `\n`/`\t`/`\"`/`\\` inside a double-quoted literal (confirmed against src/lexer.c's own
// lex_string), so any literal backslash already in `text` must be doubled here or it would
// silently start an unintended PARENA-level escape sequence instead of surviving as itself. A
// literal `"` can't appear in a StringLit's own Text (LO's lexer treats it as the closing quote),
// but patternToPCRE's own output never contains one either, so no quote-escaping is needed here.
func emitStringLiteral(text string) string {
	return "\"" + strings.ReplaceAll(text, `\`, `\\`) + "\""
}

// emitMatchIf emits a Ternary whose Cond is a Match, lowering to a real, nested Result-unwrap
// over PARENA's own regex/pcre/compile+is-match (the exact same match/Ok/Err/unbox-bool shape
// stdlib/awk.prn's own rule-matches? already uses). A compile or match failure (a real
// SyntaxError or BudgetExceededError) collapses to `false`, same as awk.prn's own real precedent
// -- not a distinct error path this v0 surfaces.
//
// Real, found-live PARENA compiler bug, confirmed in isolation (not an LO emitter mistake): ANY
// binding form (`let` OR a `match` arm's own bound name) used directly as an `if`'s own CONDITION
// fails to compile ("unknown identifier" for the bound name, referenced from anywhere inside that
// same condition) -- even though the EXACT SAME binding form compiles fine as a function's direct
// body, or as a `let`'s own body. Minimal repro confirmed against `parena build` directly:
// `(if (let [x 1] (= x 1)) 1 0)` and `(if (match r ((Ok re) re) ...) 1 0)` both fail the identical
// way. Not fixed in PARENA itself this pass (a real, separate, src/emit.c-level investigation,
// out of scope for this LO-focused pass) -- worked around here instead by fully EVALUATING the
// match chain into a plain `result` binding first (itself inside a normal `let` body position,
// which compiles fine), so the `if`'s own condition is just a bare identifier reference, never a
// binding form itself. Verified live: this exact shape compiles and runs correctly (`/tmp/
// test_matchif2.prn`-style repro, real `parena build` + `cc` + execution, exit code 1 for a real
// match).
func emitMatchIf(m parser.Match, trueExpr, falseExpr string, depth int, types []exprType) (string, error) {
	subjectStr, err := emitStringSubject(m.Subject, depth, types)
	if err != nil {
		return "", err
	}

	// patternToPCRE (pattern.go) produces the real PCRE syntax text; it can itself contain
	// literal backslashes (an Escaped atom like `\*`), so it goes through the exact same
	// PARENA-string-literal escaping as any other emitted string, not a bespoke duplicate.
	pcreText, err := patternToPCRE(m.Pattern)
	if err != nil {
		return "", err
	}
	patternStr := emitStringLiteral(pcreText)

	// Real, found-live compiler constraint, separate from the if-condition bug above: the
	// `{:max-steps N}` MatchBudget map literal can't be passed directly as a call argument --
	// `parena build` rejects it live ("map literal ... doesn't match any registered defstruct's
	// own field set", VS0 has no type context to construct an anonymous struct from at a bare
	// call site). Every real stdlib caller (grep.prn/awk.prn) binds it to a `let` first, which
	// gives the compiler somewhere to attach the inferred MatchBudget type -- so this does too.
	matchExpr := fmt.Sprintf(
		"(match (regex/pcre/compile %s budget dest) "+
			"((Ok re) (match (regex/pcre/is-match re %s dest) ((Ok mm) (regex/pcre/unbox-bool mm)) ((Err _) false))) "+
			"((Err _) false))",
		patternStr, subjectStr,
	)
	return fmt.Sprintf(
		"(let [budget {:max-steps 100000}] (let [result %s] (if result %s %s)))",
		matchExpr, trueExpr, falseExpr,
	), nil
}

// emitStringSubject resolves MATCH's own Subject to a real PARENA String expression: either a
// bare StringLit, or a LetRef/MAGNET that resolves (via `types`, exprType's own doc comment) to
// a Let binding whose own Bound was itself a StringLit -- added 2026-09-01 alongside the
// exprType tracking, closing the "Subject must be a bare LITERAL" restriction the Arena-
// threading work (S222-09) left as a real, named follow-up. Anything else (a State/Arith/
// Ternary/etc. subject, or a LetRef resolving to a typeI32 binding) is a real, honest error --
// LO still has no general type checker, so this only recognizes the one shape it can prove.
func emitStringSubject(e parser.Expr, depth int, types []exprType) (string, error) {
	switch v := e.(type) {
	case parser.StringLit:
		return emitStringLiteral(v.Text), nil
	case parser.LetRef:
		if v.Depth >= depth {
			return "", &Error{Msg: fmt.Sprintf("LetRef depth %d has no enclosing Let (only %d active here)", v.Depth, depth)}
		}
		idx := depth - 1 - v.Depth
		if idx >= len(types) || types[idx] != typeString {
			return "", &Error{Msg: "MATCH's own Subject must be a real String value (a StringLit, or a LetRef bound to one) in this v0"}
		}
		return fmt.Sprintf("x%d", idx), nil
	default:
		return "", &Error{Msg: fmt.Sprintf("MATCH's own Subject must be a real String value (a StringLit, or a LetRef bound to one) in this v0, got %T", e)}
	}
}

func arithFn(op lexer.Kind) (string, error) {
	switch op {
	case lexer.KindPlus4:
		return "base4-add", nil
	case lexer.KindMinus4:
		return "base4-subtract", nil
	case lexer.KindAnd4:
		return "base4-and", nil
	case lexer.KindOr4:
		return "base4-or", nil
	case lexer.KindXor4:
		return "base4-xor", nil
	default:
		return "", &Error{Msg: fmt.Sprintf("unsupported arithmetic operator %s", op)}
	}
}
